export const LINK_FILE_SIGNATURE='[LINK]@'
export const RAG_REWARDS = {
    REWARD_FOR_VOTE: 30,
    CONTRIBUTOR_REQUIREMENT: 10,
    REWARD_FOR_CONTRIBUTORS: 10,
    REWARD_FOR_MODEL_CREATION: 100,
    PEOPLE_WHO_GET_FIXED_REWARD: 10,
    ORDER_REWARDS_POOL: 2000,
    LIKES_REWARDS_POOL_CONTRIBUTIONS: 1000,
    LIKES_REWARDS_POOL_MODELS: 2000
}
export const DATA_FARMING_1_DEADLINE=new Date("Sep 03, 2024 20:10:30").getTime()